@startuml DiagramKlas
skinparam class {
    BackgroundColor LightYellow
    BorderColor Black
}

package "Classes" {
    package "Controllers" {

        interface IAutoryzacja(){
            + SprawdzCzyZalogowano(): void
            + SprobojZalogowac(): void
            + Wyloguj(): void

        }
        class Autoryzacja{

            + SprawdzCzyZalogowano(): void
            + SprobojZalogowac(): void
            + Wyloguj(): void
            -cssDlaNiezalogowanych(): void
        }
        class FiltrowanieKontroler
        class KontrolerDanych
        class KontrolerStrony
        class PilkarzPost
        class ZarzadzaniePilkarzami{
            # object Pilkarz
            # object Formularz

            # string id
            # string imie
            # string nazwisko
            # string awatar
            # array tablicaPost
        }

    }

    class FileLoader
    package "Helpers" {
        class BazaDanychHelper
        class FormularzHelper
    }

    package "Models" {
        class Aplikacja {
            - object Operacja
            - object Wyswietlanie
            - object SzablonHtml
            - naglowek
            - zawodnik
            - potwierdzUsuniecie

            # Wyswietl(): void
            # Usun(): void
            # Edytuj(): void
            # Zapisz(): void
            # Formularz_Dodaj(): void
            # Dodaj(): void
            # Filtry(): void
            # Szukaj(): void
            # Zaloguj(): void
            # Error404(): void
        }
        class BazaDanych {
            + Polaczenie()
            + Rozlaczenie()
            + Zapytanie()
        }
        class WyswietlaniePilkarzy{
            + WyswietlFiltrowanychPilkarzy(): void
            + WyswietlFormularzDodawania(): void
            + WyswietlFomularzEdycji(): void
            + WyswietlaniePilkarzy(): void
            + WyswietlPilkarzy(): void
            + WyswietlFiltrowanychPilkarzy(): void
            + WyswietlFormularzDodawania(): void
            + WyswietlFomularzEdycji(): void

        }

        class OperacjePilkarzy{
            + ZapiszPilkarza(): void
            + DodajPilkarza(): void
            + UsunPilkarza(): void
            + FiltrujPilkarzy(): void
            + ZapiszPilkarza(): void
            + DodajPilkarza(): void
            + UsunPilkarza(): void
            + FiltrujPilkarzy(): void
        }

        class PobieraczObrazowWikipedia{
            - API_URL
            - ANON_AVATAR
            +pobierzDaneObrazu(): void
            +pobierzZrodlo(): mixed
            +updateObrazka(): mixed
            +wyswietlObraz(): string
        }

        abstract class ZapytaniaSql{
            +getWszytkieKolumnyPilkarz(): array
            +select_Wyswietl(): string
            +liczbaZawodnikow(): string
            +select_ZawodnikById(): string
            +select_Edytuj(): string
            +update_Zapisz(): string
            +insert_Dodaj(): string
            +select_Kraj(): string
            +select_Numernakoszulce(): string
            +select_Pozycja(): string
            +select_ostaniZawodnik(): string
            +select_Awatar(): string
            +insert_Awatar(): string
            +update_Awatar(): string
            +delete_Awatar(): string
            +delete_pilkarz(): string
            +FiltrujTest(): string
            +Select_Filtruj(): string
        }
        class FiltrowanieSql{
            +getWyswietl(): string
            +setSql(): mixed
            -getImie(): string
            -getNazwisko(): string
            -getNoga(): string
            -getKraj(): string
            -getNumernakoszulce(): string
            -getPozycja(): string
            -getSortowanie(): string
            -sprawdzCzyUstawiono()
            -sprawdzWhere()
            -getWhere(): string
            -ZapytanieDlaWhere(): string
            +getCaleZapytanie(): string
        }
    }

    class Projekt {
        + FileLoader
        + Uruchom()
    }

    class SzablonHtml {
    }



    Autoryzacja --|> IAutoryzacja


    Aplikacja --> SzablonHtml
    Aplikacja --> WyswietlaniePilkarzy
    Aplikacja --> OperacjePilkarzy



    OperacjePilkarzy --> ZarzadzaniePilkarzami
    WyswietlaniePilkarzy --> ZarzadzaniePilkarzami

    ZarzadzaniePilkarzami --> ZapytaniaSql
    ZarzadzaniePilkarzami --> BazaDanychHelper
    ZarzadzaniePilkarzami --> PilkarzPost
    ZarzadzaniePilkarzami --> FormularzHelper


    FileLoader --|> Projekt



    ' Autoryzacja --|> KontrolerStrony
    ' FiltrowanieKontroler --|> KontrolerStrony
    ' PilkarzPost --|> KontrolerStrony
    ' ZarzadzaniePilkarzami --|> KontrolerStrony
    ' FileLoader --> BazaDanychHelper
    ' FileLoader --> FormularzHelper
    ' BazaDanych --> ZapytaniaSql
    ' BazaDanych --> FiltrowanieSql
    ' BazaDanych --> OperacjePilkarzy
    ' BazaDanych --> WyswietlaniePilkarzy
    ' BazaDanych --> Aplikacja
    ' WyswietlaniePilkarzy --> PobieraczObrazowWikipedia
    ' Projekt --> SzablonHtml
    ' SzablonHtml --> StronaHtml
}
@enduml
