version: '3.8'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xd
      MYSQL_DATABASE: pilkanozna
      MYSQL_USER: projekt
      MYSQL_PASSWORD: Pracownia107!
    ports:
      - "3333:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8099:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=xd
      - PMA_PORTS=3307